### ISSUE TITLE
database not created

### ISSUE THREAD

**Issue by valz77** [sanmibuh/qnap-homeassistant#10]
I have installed the qnap-homassistant qpkg on a TS-231 but it doesn't work properly. It seems it cannot create the sqlite database. Probably a problem of the Python 3 qpkg. Is there a workaround to make homeassistant work?

**Comment by sanmibuh** [comment]
I have the same problem :(
Nowadays I upgrade from TS-210 (arm) to TS-251 (x64) and I`m using official docker container.
