### ISSUE TITLE
optware deprecated

### ISSUE THREAD

**Issue by macf0x** [sanmibuh/qnap-homeassistant#7]
Optware is deprecated and no longer maintained.
Are you able to build your package with entware/qnapware instead?

**Comment by macf0x** [comment]
I've just removed the dependency for opkg and it appears to initially load without problems, with the exception that the conf directory was missing. simply creating that fixed the issue.

Will continue to test and see how it goes.

**Comment by sanmibuh** [comment]
I'll remove the dependency next week. If you can remove it before, you can send a PR.

Thank for the advise :)
